name: dbt_project
version: '1.0'
profile: dbt_project
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_project:
    staging:
      materialized: view
    core:
      materialized: incremental
    marts:
      materialized: table
